export default async function Head() {
    return (
      <>
        <title>I ❤️ Next.js 13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </>
    )
  }
  